//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by evergreen tool.
//     NOTE:Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.Evergreen.Middleware.Models
{
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Defines the <see cref="CorrelationIdMiddlewareOptions" />.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class CorrelationIdMiddlewareOptions
    {
        /// <summary>
        /// Defines the default key value for header.
        /// </summary>
        private const string DefaultHeader = "X-Correlation-ID";

        /// <summary>
        /// Defines the default key value for include in response.
        /// </summary>
        private const bool DefaultIncludeInResponse = true;

        /// <summary>
        /// Constructor for the CorrelationIdMiddlewareOptions class.
        /// </summary>
        public CorrelationIdMiddlewareOptions()
        {
            Header = DefaultHeader;
            IncludeInResponse = DefaultIncludeInResponse;
        }

        /// <summary>
        /// The header field name where the correlation ID will be stored.
        /// </summary>
        public string Header { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether IncludeInResponse
        /// Controls whether the  correlation ID is returned in the response headers.
        /// </summary>
        public bool IncludeInResponse { get; set; }
    }
}
