//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by evergreen tool.
//     NOTE:Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.Evergreen.Middleware.Models
{
    using System.Diagnostics.CodeAnalysis;
    using System.Net;

    /// <summary>
    /// Defines the <see cref="ExceptionHandlingResponseModel" />.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class ExceptionHandlingResponseModel
    {
        /// <summary>
        /// Gets or sets the CorrelationId.
        /// </summary>
        public string CorrelationId { get; set; }

        /// <summary>
        /// Gets or sets the exception Message.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the StatusCode. The default value is <see cref="HttpStatusCode.InternalServerError"/>
        /// </summary>
        public int StatusCode { get; set; } = (int)HttpStatusCode.InternalServerError;
    }
}
