//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by evergreen tool.
//     NOTE:Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.Evergreen.Middleware.Extensions
{
    using Accenture.Evergreen.Middleware.Models;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Defines the <see cref="CorrelationIdMiddlewareExtensions" />.
    /// </summary>

    [ExcludeFromCodeCoverage]
    public static class CorrelationIdMiddlewareExtensions
    {
        public static IServiceCollection AddEvergreenCorrelationIdMiddlewareOptions(this IServiceCollection services, IConfiguration configuration)
        {
            return services.Configure<CorrelationIdMiddlewareOptions>(configuration.GetSection("CorrelationIdOptions"));
        }

        /// <summary>
        /// The UseEvergreenCorrelationIdAspect.
        /// </summary>
        /// <param name="app">The app<see cref="IApplicationBuilder"/>.</param>
        /// <returns>The <see cref="IApplicationBuilder"/>.</returns>
        public static IApplicationBuilder UseEvergreenCorrelationIdAspect(this IApplicationBuilder app)
        {
            return app.UseMiddleware<CorrelationIdMiddleware>();
        }
    }
}
