//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by evergreen tool.
//     NOTE:Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accenture.Evergreen.Middleware.Extensions
{
    using Microsoft.AspNetCore.Builder;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// Defines the <see cref="ExceptionHandlingMiddlewareExtensions" />.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public static class ExceptionHandlingMiddlewareExtensions
    {
        /// <summary>
        /// The UseEvergreenExceptionAspect.
        /// </summary>
        /// <param name="builder">The builder<see cref="IApplicationBuilder"/>.</param>
        /// <returns>The <see cref="IApplicationBuilder"/>.</returns>
        public static IApplicationBuilder UseEvergreenExceptionAspect(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<ExceptionHandlingMiddleware>();
        }
    }
}
